"""Create users table

Revision ID: 3a50fdf0488e
Revises: 
Create Date: 2024-11-18 19:28:54.228375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a50fdf0488e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_data',
    sa.Column('acct_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('years_with_bank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('churn', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('risk_rating', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ave_bal', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('scheme_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mobile_app_adoption', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('internet_banking_adoption', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ussd_banking_adoption', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('digital_loan', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('unsecured_loan', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('termloan_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('credit_card', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('subsegment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_12_months_credit_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_12_months_debit_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_12_months_debit_value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('last_12_months_credit_value', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
